### ISSUE TITLE
Cannot build from the AUR

### ISSUE THREAD

**Issue by Snakehater** [coastalwhite/lemurs#134]
## Command issued:
`aur sync lemurs-git`

## Expected result:
- Lemurs is installed

## Actual result:
Output ends with:
```
==> ERROR: A failure occured in build().
        Aborting...
```

## Possible solution:
Add the rustup setup before compiling:
`rustup default stable`

## Note
Above solution fixed the issue for me

## Device info:
Linux 6.2.2-arch1-2-surface

**Comment by coastalwhite** [comment]
Hey, thank you for reporting!

There is some logic in there now to ensure `stable` is installed and used. Is there any chance you were on an older version of rust and running `rustup default stable` just updated rust?

To be honest, I really don't want to add `rustup default stable` since it messes up any environment you might have set up already. Arguably, we may have to add some checking for the MSRV, but even updating is rather volatile. Ideally, we would ship mostly ship precompiled binaries instead.

**Comment by Absobel** [comment]
Maybe the fact that `rustup default stable` could be needed to build the package could be added to the readme ? (I'm a new arch user so I don't know if it's something that is supposed to be obvious or not, ngl)

**Comment by coastalwhite** [comment]
I had another look at this problem. I just messed up the AUR `PKGBUILD` script. It is fixed.

**Comment by pmrv** [comment]
I ran into a similar issue, because my rust toolchain was out of date (on a freshly installed laptop).  Building with cargo in the source directory or installing via a aur helper gave this error

```
error: failed to parse manifest at `/home/ponder/software/lemurs/Cargo.toml`

Caused by:
  feature `edition2021` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["edition2021"]` to enable this feature
```

`rustup update` fixed it.  Not sure if it makes sense to run this by default in `PKGBUILD`, but I thought I'd mention it here for posterity.
