### ISSUE TITLE
systemd-homed

### ISSUE THREAD

**Issue by tiagocpontesp** [coastalwhite/lemurs#168]
```lemurs::auth] Authentication failed for 't'. Reason: Login creditionals are valid, but username is not found. This should not be possible :(```

tried messing about with the pam file, to no avail.

**Comment by coastalwhite** [comment]
Thank you for bringing this issue to my attention.

This is an error for when PAM authenticates a user, but your user is not found in the `/etc/passwd`. Ideally, we won't have a hard dependency on the `/etc/passwd` file, since that doesn't work for certain configurations.

Are you using any weird authentication scheme or are on a distribution that handles authentication a bit differently?

**Comment by tiagocpontesp** [comment]
and thank you for this project :)
regular homed setup on arch, currently using greetd w/o any particularities.

**Comment by coastalwhite** [comment]
Is there any chance you could try again? We changed the upstream way we load user data, which should prevent this issue.

**Comment by tiagocpontesp** [comment]
sure, just saw this. within a few hours likely -- within a day certain.

**Comment by JeremiahSecrist** [comment]
> and thank you for this project :) regular homed setup on arch, currently using greetd w/o any particularities.

Currently trying to figure out greetd + lemurs right now. Would you be willing to share your setup?

**Comment by tiagocpontesp** [comment]
@coastalwhite working, thanks :)
@JeremiahSecrist greetd + lemurs is a bit strange since they're fulfilling the same function afaik
